openapi: 3.0.0
info:
  title: API de Gerador de QR Code
  description: Uma API simples para gerar QR Codes a partir de texto.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /generate-qr:
    post:
      summary: Gerar QR Code
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: QR Code gerado com sucesso
          content:
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: Solicitação inválida
